### ISSUE TITLE
Milestone: Individual Player pages

### ISSUE THREAD

**Issue by TptMike** [Everneth/RP-Dashboard#1]
With the player list page complete with pagination and being filterable, the next step is to click on individual player names to see their individual stats, guild info, advancements, etc.

This should be as easy as setting up a route expecting a UUID in the GET request.

- [x] Setup GET route expecting UUID in the route request
- [x] Successfully return player page view showing IGN and UUID
- [ ] Create playerdata cache layer to store local copies of the player advancement JSON and stats JSON
- [x] Fetch and filter JSON data to present in the view
- [ ] Organize player profile as a personal dashboard

**Comment by TptMike** [comment]
3/5 tasks done in the latest push. Cache layer will need to be completed for 1 task. Dashboard will come after a few more UI components are built.
