### ISSUE TITLE
Milestone: Individual guild pages

### ISSUE THREAD

**Issue by TptMike** [Everneth/RP-Dashboard#2]
With the guild list page complete, the next logical step is to click on guilds individually to view their roster, their colors, leadership info, and, RP status and score.

- [x] Setup GET route expecting guild ID in the route
- [x] Successfully return guild view showing guild name, tier, colors, and score
- [x] Successfully return guild roster as a table
- [x] Link players to their player pages on the roster

**Comment by TptMike** [comment]
All tasks are completed in this ticket. More styling work needs to be done though
