### ISSUE TITLE
Milestone: Data caching layer

### ISSUE THREAD

**Issue by TptMike** [Everneth/RP-Dashboard#3]
Any API call should cache data locally to reduce the amount of HTTP requests made for performance reasons. 2 approaches can be made:

1. Store the data retrieved from the API in the database either by utilizing a plugin and caching query results locally
2. Store the data retrieved from the API as JSON and create a microservice to update these files in batches based on modify date.

So far the approach chosen is 2.

A change on the API side may be required to check for modify date. I would rather only update files that have a modify date less than 12 hours old so as to only update the most recently changed files in the batch rather than blanket everything. Another ticket will be needed in the API plugin repo for this feature.

- [ ] Create thread queue with a worker pool (if possible in PHP??)
- [ ] Send API request for a batch of 100 JSON objects (expecting a collection of 50 to 100 objects containing each players stats/advancements
- [ ] Parse JSON data updating local JSON files using the new data from the API returned data
- [ ] Send a new API request for the next 100 JSON objects
- [ ] Upon completion, log the results of the task in a log file

**Comment by TptMike** [comment]
After reading more into the docs of Laravel, this app can leverage built in queueing and fetch all json data once a day and then do on-demand fetches based on age of the file. Parsers are still required to filter out all the junk recipe data, etc and logging the jobs ran would be beneficial
