### ISSUE TITLE
Milestone: Logs section

### ISSUE THREAD

**Issue by TptMike** [Everneth/RP-Dashboard#4]
As the system grows, more error checking is required and the task logs from the data caching layer will need to be more easily accessible. This system should be scalable to include error logs in future, task logs from any worker queues or cron jobs, and admin logs once discord based authorization is baked in.

- [ ] Read in and paginate log as a table
- [ ] Include controls to filter log based on description or severity
- [ ] Include controls to clear the log

**Comment by TptMike** [comment]
Logs are read in from a json file stored on the local FS. It is currently not paginated though this would take minimal work.
