### ISSUE TITLE
[EPIC] Todos before go-live of Season 10

### ISSUE THREAD

**Issue by TptMike** [Everneth/RP-Dashboard#7]
### Medals
- [ ] Create modal with toast message
- [ ] Edit modal with toast message
- [ ] Delete logic with toast message
- [ ] Award screen and form with toast message
- [ ] Validate order of precedence on player profiles
### Characters
- [ ] Character list
- [ ] Character create modal with toast message
- [ ] Character edit modal with toast message
- [ ] Character delete with toast message
- [ ] Validate character info shows on player profiles
### Activities
- [ ] New activities table created in the DB
- [ ] EMI updated to log specific events to the DB
- [ ] Jasper updated to log specific events to the DB
- [ ] Populate and paginate activies in player profile Activities tab
- [ ] Log timestamp of leaving the server for last seen data
- [ ] Log discord member leaves to track who is not in discord in profile
### JSON Data
- [ ] Create cronjob to copy data into laravel data store
- [ ] Create worker queues in laravel to move data to discord id or ign UUID based player folders
- [ ] Add logic to manually request a sync on the profile page and use worker queue system
- [ ] Add logic to Jasper to update roles cache for syncing to player profiles
- [ ] Add logic to laravel to split roles data by discord id and store in player laravel data store
### NBT Data
- [ ]  Parse scoreboard dat file and cache
### Map
- [ ]  Add map Iframe to map view
### Player profile data linking
- [ ] Add scoreboard team to Teams data on player profile
- [ ] Parse and add stats json data to Stats tab
- [ ] Parse and add advancements json data to Advancements tab
- [ ] Add Discord roles to Discord info tab using split roles cache
### Player Profile editor
- [ ] Add player profile editor screen
- [ ] Add player_seasons DB table to store per season data for historical card
- [ ] Add season editor inside profile editor screen
- [ ] List all historical season records
- [ ] Create historical season record with toast message
- [ ] Edit historical season record with toast message
- [ ] Delete historical season record with toast message
- [ ] About me field
### Discord authentication API with Socialite
- [ ] Add OAuth bot in Discord Developers portal
- [ ] Add callback and redirect URLs to socialite config
### Discord authorization using cached roles
- [ ] Simple Permissions leveraging existing discord roles and hard coded IDs
